In [137]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

import matplotlib.pyplot as plt

datasets = load_digits()
X,y = datasets.data,datasets.target
#print('total :',len(X))

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2)
# print('X_train',len(X_train))
# print('X_test',len(X_test))

# index = 1

# plt.suptitle(datasets.target_names[y_train[index]])
# plt.subplot(1,1,1)
# plt.imshow(X_train[index].reshape(8,8))
# plt.show()

clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
print('score train set',clf.score(X_train,y_train))

y_predict = clf.predict(X_test)
print('score test set',clf.score(X_test,y_test))

print('accuracy score :',accuracy_score(y_test,y_predict))
print('confusion matrix :\n',confusion_matrix(y_test,y_predict))
print('classification report :\n',classification_report(y_test,y_predict))


score train set 1.0
score test set 0.8638888888888889
accuracy score : 0.8638888888888889
confusion matrix :
 [[40  0  0  0  1  0  0  0  1  0]
 [ 0 23  2  0  0  2  2  0  1  0]
 [ 1  1 31  0  0  1  0  0  0  0]
 [ 0  0  2 30  0  0  0  3  0  3]
 [ 0  1  1  0 35  0  0  0  0  1]
 [ 0  0  0  0  2 29  1  0  1  0]
 [ 1  0  0  1  1  0 33  1  0  0]
 [ 0  0  0  2  2  0  1 25  1  0]
 [ 0  2  5  0  2  0  0  0 29  2]
 [ 0  0  0  0  0  0  0  1  0 36]]
classification report :
               precision    recall  f1-score   support

           0       0.95      0.95      0.95        42
           1       0.85      0.77      0.81        30
           2       0.76      0.91      0.83        34
           3       0.91      0.79      0.85        38
           4       0.81      0.92      0.86        38
           5       0.91      0.88      0.89        33
           6       0.89      0.89      0.89        37
           7       0.83      0.81      0.82        31
           8       0.88      0.72      0.79    